/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/check_ball.check.c" instead.
 */

#include <check.h>

#line 1 "tests/check_ball.check.c"
#include "main.h"

// unit testing below
// checkmk tests/check_ball.check.c > tests/check_ball.c
START_TEST(calculate_velocity_inelastic_collision)
{
#line 6
    fail_unless(calculate_velocity_elastic_collision(100.f) == -90.f, "Incorrect velocity calculation");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, calculate_velocity_inelastic_collision);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
